spring:
  profiles:
    active: dev
  application:
    name: crud-service

dicts:
  firstDict:
    key: first_dict
  secondDict:
    key: second_dict

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/zaliczenie-db
    username: postgres
    password: ld112358
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8082

dicts:
  service:
    url: http://127.0.0.1:8081/dict_values

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 0
