spring:
  profiles:
    active: prod
  application:
    name: crud-service

dicts:
  service:
    name: dict-service
    endpoint: dict_values
  firstDict:
    key: first_dict
  secondDict:
    key: second_dict

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/zaliczenie-db
    username: postgres
    password: ld112358
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 0

