version: '3.8'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data-vol:/var/lib/postgresql/data
      - ./db_schema/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    ports:
      - 5433:5432
    networks:
      - internal
  
  eureka:
    image: eureka-server:latest
    restart: always
    networks:
      - internal
    ports:
      - 8761:8761

  api-gateway:
    image: api-gateway:latest
    restart: always
    depends_on:
      - eureka
    networks:
      - internal
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
    ports:
      - 8080:8080
  
  oauth2-acs:
    image: oauth2-acs:latest
    restart: always
    depends_on:
      - eureka
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/${DB_NAME}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      oauth2.clientId: ${OAUTH2_CLIENT_ID}
      oauth2.password: ${OAUTH2_PASSWORD}

    ports:
      - 9000:9000
    networks:
      - internal

  dict-service:
    image: dict-service:latest
    restart: always
    depends_on:
      - db
      - eureka
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/${DB_NAME}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
    networks:
      - internal

  crud-service:
    image: crud-service:latest
    restart: always
    depends_on:
      - db
      - eureka
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/${DB_NAME}
      spring.datasource.username: ${DB_USER}
      spring.datasource.password: ${DB_PASSWORD}
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
    deploy:
      mode: replicated
      replicas: 2
    networks:
      - internal

volumes:
  db-data-vol:

networks:
  internal: