version: '3.8'

services:
  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data-vol:/var/lib/postgresql/data
      - ./db_schema/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql
    ports:
      - 5433:5432
    networks:
      - internal

volumes:
  db-data-vol:

networks:
  internal: