server:
  port: 8080

spring:
  profiles:
    active: prod
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: crud_service
          uri: lb://crud-service
          predicates:
            - Path=/simple_entity/**
        - id: dict_service
          uri: lb://dict-service
          predicates:
            - Path=/dict_values/**
        - id: ai_api_consumer
          uri: lb://ai-api-consumer
          predicates:
            - Path=/image/**

---

spring:
  config:
    activate:
      on-profile: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://oauth2-acs:9000

---

spring:
  config:
    activate:
      on-profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
