server:
  port: 8081

logging:
  level:
    reactor:
      netty:
        http:
          client: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: password
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8081/authorized"
            scope: read_write
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: "http://oauth2-acs:9000"

app:
  api:
    home:
      url: "http://127.0.0.1:8080"
    endpoints:
      dict: "/dict_values"
      crud: "/simple_entity"